In [1]:
import openpyxl
from openpyxl import load_workbook
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
%matplotlib notebook

In [2]:
df = pd.read_excel("dataset.xlsx", sheet_name=None, header=0)

# Section 4.1-(2) Table 4.1.2, Table 4.1.3, Table 4.1.4

In [3]:
all_df = {}
for i, d in enumerate(df.items()):
    name, data = d
    all_df[name] = data

In [4]:
data = all_df['1K-01']
#data_test = all_df['1X-02']

In [5]:
data = data[data['DEPTH'] == data["DEPTH"]]   # drop NaN value row
#data_test = data_test[data_test['DEPTH'] == data_test["DEPTH"]]   # drop NaN value row

In [6]:
data = data.drop(["Core_Facies"], axis=1)
#data_test = data_test.drop(["Core_Facies"], axis=1)

In [7]:
data['Log_Facies'].apply(lambda x: str(x)).describe()

count     1025
unique       3
top        1.0
freq       530
Name: Log_Facies, dtype: object

## Table 4.1.2

In [8]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

In [9]:
X = data[["DEPTH", "CALI", "DT", "GR", "LLD", "LLS", "MSFL", "NPHI", "RHOB"]]
ss = StandardScaler()
X = ss.fit_transform(X)
X_real = data[["DEPTH", "CALI", "DT", "GR", "LLD", "LLS", "MSFL", "NPHI", "RHOB"]]

In [10]:
Y = data['Log_Facies'].apply(lambda x: int(x)-1)
#Y_test = data_test['Log_Facies'].apply(lambda x: int(x)-1)

In [11]:
clf = LogisticRegression()
clf_real = LogisticRegression()

In [12]:
clf.fit(X, Y)
clf_real.fit(X_real, Y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [13]:
#Y_pred = clf.predict(X)
#Y_real_pred = clf.predict(X_real)

In [14]:
print(clf.intercept_)
print(clf.coef_)

[-0.23088812 -0.38637902 -5.331887  ]
[[ 0.06540731 -0.20490059 -0.99202325  0.27874922  1.01387764 -1.51442859
   1.15717478 -1.24748841 -3.56451337]
 [ 1.13719754 -0.03029435  0.6867362   0.05459472  0.9444873  -0.12385016
  -0.68960912  0.41124826  1.68873727]
 [-3.2547469   1.09666476  0.09938329  0.08917029 -1.33224463  0.83745061
   0.0253272   0.24571485  1.03975919]]


## Table 4.1.3

In [15]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

In [16]:
X = data[[ "DT", "GR", "LLD","LLS", "MSFL", "NPHI", "RHOB"]]
ss = StandardScaler()
X = ss.fit_transform(X)
X_real = data[["DT", "GR", "LLD","LLS", "MSFL", "NPHI", "RHOB"]]

In [17]:
Y = data['Log_Facies'].apply(lambda x: int(x)-1)
#Y_test = data_test['Log_Facies'].apply(lambda x: int(x)-1)

In [18]:
clf = LogisticRegression()
clf_real = LogisticRegression()

In [19]:
clf.fit(X, Y)
clf_real.fit(X_real, Y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [20]:
print(clf.intercept_)
print(clf.coef_)

[-0.22783051 -0.41209408 -4.53286501]
[[-9.58290213e-01  2.87270199e-01  1.12666978e+00 -1.62000297e+00
   1.13446117e+00 -1.30221804e+00 -3.62549668e+00]
 [ 8.08546723e-01 -4.16038778e-01  4.54935680e-01 -2.79421028e-01
  -7.17659678e-01  1.91421526e-01  1.85087969e+00]
 [-4.26452299e-01  1.21169528e+00 -2.10329285e+00  2.80897558e+00
   1.58791951e-03  6.56627826e-01  9.20568782e-01]]


## Table 4.1.4

In [21]:
all_df = {}
for i, d in enumerate(df.items()):
    name, data = d
    all_df[name] = data
all_data = pd.concat(df.values())

In [22]:
all_data = all_data[[ "DEPTH", "DT", "GR", "LLD", "NPHI", "RHOB", "Log_Facies"]]
all_data = all_data.dropna(axis=0, how='any')
data = all_data

In [23]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

In [24]:
X = data[["DEPTH", "DT", "GR", "LLD", "NPHI", "RHOB",]]
ss = StandardScaler()
X = ss.fit_transform(X)
Y = data['Log_Facies'].apply(lambda x: int(x)-1)

In [25]:
clf = LogisticRegression()

In [26]:
clf.fit(X, Y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [27]:
Y_pred = clf.predict(X)

In [28]:
from sklearn.metrics import confusion_matrix 

In [29]:
#results = confusion_matrix(Y, Y_pred)
#results
#from sklearn.metrics import classification_report
#report = classification_report(Y, Y_pred)
#print(report)

In [30]:
print(clf.intercept_)
print(clf.coef_)

[ 0.78055015 -1.04563358 -4.77313397]
[[ 0.36258517 -0.11776839 -0.0184775  -0.19050506 -2.63032929 -4.02616705]
 [-0.09633896 -0.08903942 -0.23619461 -0.06511261  1.26371285  1.94912398]
 [-0.95162169  0.12162854  1.19518554  0.61236001  0.48844301  1.46698523]]


In [31]:
#Y_binary = data['Log_Facies'].apply(lambda x: 1 if int(x)==1 else 0)
#clf_binary = LogisticRegression()
#clf_binary.fit(X, Y_binary)
#print(clf_binary.intercept_)
#print(clf_binary.coef_)